### PR TITLE
Switch CI to use GitHub Actions

### PR DESCRIPTION
**Pull request by fingolfin**
This is necessary as Travis CI started to require payment for its services.

This also attempts to restore the CI variants with and without ferret, which broke in PR #6

### CODE REVIEW

**Comment by fingolfin** [comment]
@ChrisJefferson fails in GAP 4.10 with ferret, perhaps due to an incompatible change somewhere? Perhaps we should not clone the latest ferret but rather just use the one bundled with GAP (perhaps except when testing against GAP master)??

**Comment by ChrisJefferson** [comment]
I'm happy to just drop 4.10 support (as I wouldn't expect us to make any more releases of it) -- I'm happy for you to drop that line, or I can make a new PR which extends this and removes it.

**Comment by fingolfin** [comment]
@ChrisJefferson you realize you can edit this PR? :-)

**Comment by fingolfin** [comment]
I've updated the PR, and also switch things to use the new names of our Actions.

**Review by olexandr-konovalov — APPROVED** [review]

**Pull request merged**
